FROM python:3.9.7-slim
ENV PYTHONUNBUFFERED 1

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.8.0/wait /wait
RUN chmod +x /wait

COPY app/ /app/
COPY requirements.txt /app/requirements.txt
WORKDIR /app

RUN pip install --upgrade pip && \
pip install -r /app/requirements.txt && \
pip install ipython
